markdown: redcarpet
highlighter: rouge
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "fenced_code_blocks", "with_toc_data"]
theme: jekyll-theme-cayman
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
  gfm_quirks: paragraph_end
