theme: jekyll-theme-modernist
timezone: America/New_York
markdown: kramdown
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
      title: "Homeless Human"
